import {
  siApache,
  siAstro,
  siClaude,
  siCloudflare,
  siGit,
  siInsomnia,
  siJira,
  siCss,
  siDotnet,
  siDocker,
  siFigma,
  siFirebase,
  siGithubactions,
  siGo,
  siGooglecloud,
  siGraphql,
  siHtml5,
  siHugo,
  siJavascript,
  siLaravel,
  siLumen,
  siMysql,
  siNginx,
  siNodedotjs,
  siNuxt,
  siPhp,
  siPostgresql,
  siPython,
  siReact,
  siRedis,
  siRust,
  siSass,
  siSvelte,
  siTailwindcss,
  siTypescript,
  siVuedotjs,
} from 'simple-icons';

export const iconMap: Record<string, { path: string; title: string }> = {
  'Apache':         siApache,
  'Astro':          siAstro,
  'Claude':         siClaude,
  'Cloudflare':     siCloudflare,
  'CSS':            siCss,
  'Git':            siGit,
  'Insomnia':       siInsomnia,
  'Jira':           siJira,
  '.NET':           siDotnet,
  'Docker':         siDocker,
  'Figma':          siFigma,
  'Firebase':       siFirebase,
  'GitHub Actions': siGithubactions,
  'Go':             siGo,
  'GCP':            siGooglecloud,
  'GraphQL':        siGraphql,
  'HTML':           siHtml5,
  'Hugo':           siHugo,
  'JavaScript':     siJavascript,
  'Laravel':        siLaravel,
  'Lumen':          siLumen,
  'MySQL':          siMysql,
  'Nginx':          siNginx,
  'Node.js':        siNodedotjs,
  'Nuxt':           siNuxt,
  'PHP':            siPhp,
  'PostgreSQL':     siPostgresql,
  'Python':         siPython,
  'React':          siReact,
  'Redis':          siRedis,
  'Rust':           siRust,
  'SCSS':           siSass,
  'Svelte':         siSvelte,
  'Tailwind CSS':   siTailwindcss,
  'TypeScript':     siTypescript,
  'Vue.js':         siVuedotjs,
  // Custom icon — server stack (no brand icon available)
  'Amazon Web Services': {
    title: 'Amazon Web Services',
    path: 'M4 2a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H4zm0 7a1 1 0 1 1 0-2 1 1 0 0 1 0 2zm3 0a1 1 0 1 1 0-2 1 1 0 0 1 0 2zM4 13a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-4a2 2 0 0 0-2-2H4zm0 7a1 1 0 1 1 0-2 1 1 0 0 1 0 2zm3 0a1 1 0 1 1 0-2 1 1 0 0 1 0 2z',
  },
};

export const hasIcon = (name: string): boolean => name in iconMap;

export const urlMap: Record<string, string> = {
  'Apache':               'https://httpd.apache.org',
  'Amazon Web Services':  'https://aws.amazon.com',
  'Astro':                'https://astro.build',
  'Claude':               'https://claude.ai',
  'Cloudflare':           'https://cloudflare.com',
  'CSS':                  'https://developer.mozilla.org/docs/Web/CSS',
  '.NET':                 'https://dotnet.microsoft.com',
  'Docker':               'https://docker.com',
  'Figma':                'https://figma.com',
  'Firebase':             'https://firebase.google.com',
  'GCP':                  'https://cloud.google.com',
  'Git':                  'https://git-scm.com',
  'GitHub Actions':       'https://github.com/features/actions',
  'Go':                   'https://go.dev',
  'GraphQL':              'https://graphql.org',
  'HTML':                 'https://developer.mozilla.org/docs/Web/HTML',
  'Hugo':                 'https://gohugo.io',
  'Insomnia':             'https://insomnia.rest',
  'JavaScript':           'https://developer.mozilla.org/docs/Web/JavaScript',
  'Jira':                 'https://atlassian.com/software/jira',
  'Laravel':              'https://laravel.com',
  'Lumen':                'https://lumen.laravel.com',
  'MySQL':                'https://mysql.com',
  'Nginx':                'https://nginx.org',
  'Node.js':              'https://nodejs.org',
  'Nuxt':                 'https://nuxt.com',
  'PHP':                  'https://php.net',
  'PostgreSQL':           'https://postgresql.org',
  'Python':               'https://python.org',
  'React':                'https://react.dev',
  'Redis':                'https://redis.io',
  'Rust':                 'https://rust-lang.org',
  'SCSS':                 'https://sass-lang.com',
  'Svelte':               'https://svelte.dev',
  'Tailwind CSS':         'https://tailwindcss.com',
  'TypeScript':           'https://typescriptlang.org',
  'Vue.js':               'https://vuejs.org',
};
